# Generated by Codex on 2026-04-03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RouteSearchLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_at', models.DateTimeField()),
                ('priority_mode', models.CharField(default='optimal', max_length=24)),
                ('selected_transport', models.JSONField(blank=True, default=list)),
                ('selected_carriers', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logged_from_searches', to='cities.city')),
                ('to_city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logged_to_searches', to='cities.city')),
                ('via_city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logged_via_searches', to='cities.city')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
