# Generated by Codex on 2026-04-03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('slug', models.SlugField(max_length=160, unique=True)),
                ('region', models.CharField(blank=True, default='', max_length=128)),
                ('population', models.PositiveIntegerField(default=0)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('has_airport', models.BooleanField(default=False)),
                ('has_train_station', models.BooleanField(default=False)),
                ('has_bus_station', models.BooleanField(default=False)),
                ('has_commuter_station', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
