# Generated by Codex on 2026-04-03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('carriers', '0001_initial'),
        ('cities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=128, unique=True)),
                ('transport_type', models.CharField(choices=[('plane', 'Plane'), ('train', 'Train'), ('bus', 'Bus'), ('electric_train', 'Electric train')], max_length=24)),
                ('departure_datetime', models.DateTimeField()),
                ('arrival_datetime', models.DateTimeField()),
                ('duration_minutes', models.PositiveIntegerField()),
                ('price', models.PositiveIntegerField()),
                ('distance_km', models.PositiveIntegerField()),
                ('is_direct', models.BooleanField(default=True)),
                ('available_seats', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('last_synced_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('carrier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='carriers.carrier')),
                ('from_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets_from', to='cities.city')),
                ('to_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets_to', to='cities.city')),
            ],
            options={
                'ordering': ('departure_datetime', 'price'),
                'indexes': [models.Index(fields=['from_city', 'departure_datetime', 'is_active'], name='tickets_tic_from_ci_ba4455_idx'), models.Index(fields=['from_city', 'to_city', 'departure_datetime'], name='tickets_tic_from_ci_77dfbe_idx'), models.Index(fields=['transport_type', 'departure_datetime', 'is_active'], name='tickets_tic_transpo_67890f_idx'), models.Index(fields=['carrier', 'departure_datetime'], name='tickets_tic_carrier_8d92b7_idx'), models.Index(fields=['is_active', 'departure_datetime'], name='tickets_tic_is_acti_8fe647_idx')],
            },
        ),
    ]
