# Generated by Django 5.2.12 on 2026-04-03 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='ticket',
            new_name='tickets_tic_from_ci_85bbfa_idx',
            old_name='tickets_tic_from_ci_ba4455_idx',
        ),
        migrations.RenameIndex(
            model_name='ticket',
            new_name='tickets_tic_transpo_51ace4_idx',
            old_name='tickets_tic_transpo_67890f_idx',
        ),
        migrations.RenameIndex(
            model_name='ticket',
            new_name='tickets_tic_carrier_262565_idx',
            old_name='tickets_tic_carrier_8d92b7_idx',
        ),
    ]
